export { default as Main } from "./Main/Main";
export { default as Board } from "./Board/Board";
export { default as BoardRow } from "./BoardRow/BoardRow";
export { default as PickerBox } from "./PickerBox/PickerBox";
export { default as Color } from "./Color/Color";
export { default as Target } from "./Target/Target";
export { default as SolutionItem } from "./SolutionItem/SolutionItem";
export { default as SolutionResult } from "./SolutionResult/SolutionResult"
export { default as DoneAction } from "./Actions/DoneAction";
export { default as BackAction } from "./Actions/BackAction";
export { default as Celebrate } from "./Celebrate/Celebrate";
export { default as GameResult } from "./GameResult/GameResult";